name: Test

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for SonarQube to analyze git history

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18" # Using Node 18 which is more stable for React Native
          cache: "npm" # Cache npm dependencies for faster runs

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Run tests with coverage
      - name: Run tests
        run: npm run test:ci

      # Upload coverage results
      - name: Upload coverage results
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/
          retention-days: 5
